### ISSUE TITLE
ExpandAsArray Query Bug

### ISSUE THREAD

**Issue by rnosworthy** [qcubed/framework#667]
I'm on version 2.2.3

I have 3 objects with the following relationships

Foo reverse reference to Bar where Bar.foo_id has a unique constraint.
Bar has a many to many with Baz.

If I perform this sort of query:

Foo::LoadAll(QQ:Clause(
	QQ::ExpandAsArray(QQN::Foo()->Bar->Baz)
)

There is an error thrown: Undefined GET property or variable in ‘Foo' class: _objBar

As far as I can see there code in Foo::ExpandArray() that suggests the $strVarName for the object ‘Bar' should be prefixed with '_obj' but it is in fact just ‘obj’. 

Am I doing this wrong or do you have any idea on how to fix this or is this kind of query not supported.

Edit to add some information:

Defined in the FooGen class I see this for defining the member object

///////////////////////////////
// PROTECTED MEMBER OBJECTS
///////////////////////////////

protected $objBar;

Also, above the class for QQNodeFoo extends QQNode {

I see this :
* @property-read QQReverseReferenceNodeBar $Bar

So I believe codegen and the query engine could have some sort of conflict for this type of relationship

**Comment by spekary** [comment]
ExpandArray was quite broken in 2.2.3. I fixed it in the alpha3 build, though I do not believe the specific relationship you are mentioning has been tested. The fix was difficult. $objBar is the right thing for it to be looking for because of the unique reverse relationship, but ExpandArray is confused, because it does not know what kind of node it is dealing with. 3.0 was changed to keep the node information.

So, the short answer is that ExpandArray in 2.2.3 cannot handle the kind of relationship you are giving it.

**Comment by kpirbhai** [comment]
This is still a problem in the 2.3 stable release. The code gen template has ExpandAsArrayNodes where the QQuery.class.php has __get()......    case "ExpandAsArrayNode".

It is just a pluralization problem but it is breaking the entire code gen process. 

It would be wonderful to actually fix this and push it to the 2.3 version that is being shown on the home page of qcu.be as the whole framework codegen is useless in the current state for anyone not familiar with the framework.

**Comment by kpirbhai** [comment]
For anyone who comes across this, I made the following change and everything seems to be working well.

includes/qcubed/_core/framework/QQuery.class.php

change line 1999 from:

`case 'ExpandAsArrayNode':`


to:

`case 'ExpandAsArrayNodes':`
